// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgtICxJh6XV0GPw-WjJ1rw0FPnhRTC_Oo',
    appId: '1:435318308339:web:2754b02ea1b41e51b16686',
    messagingSenderId: '435318308339',
    projectId: 'domini-35e8e',
    authDomain: 'domini-35e8e.firebaseapp.com',
    storageBucket: 'domini-35e8e.appspot.com',
    measurementId: 'G-N6NNZS0ZLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMrU_LKjcDlbC9BtiVezJHB2ur_VDAjic',
    appId: '1:435318308339:android:ccb156a40c6a2569b16686',
    messagingSenderId: '435318308339',
    projectId: 'domini-35e8e',
    storageBucket: 'domini-35e8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfrz9dw77GNZxADKX-v9JK5PFZ9Ozrw9s',
    appId: '1:435318308339:ios:d91b1c4621516dc9b16686',
    messagingSenderId: '435318308339',
    projectId: 'domini-35e8e',
    storageBucket: 'domini-35e8e.appspot.com',
    iosClientId: '435318308339-0nnqeh41ass2jlk0sr3q4rjopcg5ei10.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitoka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfrz9dw77GNZxADKX-v9JK5PFZ9Ozrw9s',
    appId: '1:435318308339:ios:d9f03311c37d3094b16686',
    messagingSenderId: '435318308339',
    projectId: 'domini-35e8e',
    storageBucket: 'domini-35e8e.appspot.com',
    iosClientId: '435318308339-ao6gc8a3nohbmlqpjl63a4g6iethslij.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication5.RunnerTests',
  );
}
